/*THIS DOCUMENT WAS CREATED TO FILL THE DATABASE MODEL AT STARTUP*/

module.exports = {
    criteria : [
        /*CRITERIA*/
        {code:1,       label: 'cri_supportOnArrivalandVisa',     shortName:"Support",                               name:"Support given by school before and upon arrival", description: 'How has the school helped you take care of everything that was needed in the process of moving to China, was it present or did it leave you on your own? Upon immediate arrival, did the school have staff dedicated to help you with the sometimes unpleasant transition experienced when moving to a new country?'},
        {code:2,       label: 'cri_managementAdministration',    shortName:"Environment",                    name:"Work environment and management",                 description: 'Was the work environment agreeable and welcoming? Was the dynamic between foreign teachers and the rest of the school staff united or was communication sometimes difficult. In addition, think about your experience dealing with management, have you had any problems or was everything dealt with professionally.'},
        {code:3,       label: 'cri_resourcesAvailability',       shortName:"Resources",                               name:"Academic Resources",                              description: 'Did your school provide the ressources necessary(curriculums, workbooks, computers) to prepare your classes, or were you left to do most of it on your own.'},
        {code:4,       label: 'cri_accomodationProvided',        shortName:"Accomodation",                                  name:"Reliability of Provided Accomodation",            description: 'Were you provided with the accomodation formula promised either by phone or through the contract. Is it big enough, clean, and ready for new teachers arrival, are utilities functioning properly? (gas, water, electricity, shower, stove, etc. )'},
        {code:5,       label: 'cri_locationAccesibility',        shortName:"Location",                       name:"Location and accessibility",                      description: 'Is the school well situated? Is accessibility or remoteness become an issue, do you have to take an hour bus to be anywhere?'},
        {code:6,       label: 'cri_salaryVsCOLiving',            shortName:"Salary",              name:"Salary, workload and cost of living",             description: 'After having settled down and covered most initial expenses, do you believe the salary is reasonable in terms of the amount of work expected from you as well as in accordance to the cost of living there? How does it compare to that of other schools in the same area?'},
        {code:7,       label: 'cri_respectForContract',          shortName:"Contract",                             name:"Attention given to respecting contract",          description: 'Contracts can sometimes be overlooked when circumstances become trying, favors are done to help out. But if it is a constant battle to keep your workload within the negociated terms, then the contract is not being respected. What was your experience in dealing with workload, accomodation and holidays?'},
        {code:8,       label: 'cri_dynamicTeachers',             shortName:"Dynamic",                         name:"Dynamic amongst Teachers",                        description: 'In a place like China, given the language and cultural barriers, your colleagues and your friends are often the same people, and ultimately they will shape your experience.'}
    ]
}